# Pytest configuration file
# -Adds project root to PITHONPATH
# -Tells pytest to collect tests from the "tests" folder
# Così quando nei vari test viene chiamato planner.py python sa dove andare a prenderlo, cioè nella root del progetto

[pytest]
pythonpath= .
testpaths=tests
